### ISSUE TITLE
Timeout connect

### ISSUE THREAD

**Issue by colixxx** [newAM/hisensetv#10]
Hi! I try use it, but i can't authorize on TV.

```
hisensetv 10.0.0.198 --authorize --no-ssl -v
Traceback (most recent call last):
  File "/usr/local/bin/hisensetv", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/hisensetv/__main__.py", line 61, in main
    with tv:
  File "/usr/local/lib/python3.9/site-packages/hisensetv/__init__.py", line 128, in __enter__
    raise HisenseTvTimeoutError(f"failed to connect in {self.timeout:.3f}s")
hisensetv.HisenseTvTimeoutError: failed to connect in 10.000s
```

My TV: 
model: 65A7500F
version: V0000.01.00T.K1112

**Comment by newAM** [comment]
Are you able to nmap port 36669 on your TV?  First step is to see if the socket is listening on the TV.

```
nmap -p 36669 10.0.0.198
```

**Comment by colixxx** [comment]
Hi! Thanks for answe!
Yes, socket is listening
```
nmap -p 36669 10.0.0.198
Starting Nmap 7.91 ( https://nmap.org ) at 2021-01-18 18:13 MSK
Nmap scan report for 10.0.0.198
Host is up (0.0038s latency).

PORT      STATE SERVICE
36669/tcp open  unknown

Nmap done: 1 IP address (1 host up) scanned in 0.10 seconds
```

**Comment by newAM** [comment]
Hmmm.  Just double checking: the API has been authorized (see README), and have you tried without `--no-ssl`?

If those two things don't solve it I think the next step is a wireshark capture of both this API, and if you can, one of the mobile app (if it works on your device, it doesn't work on mine).
